name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --all-features --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run clippy
        run: cargo clippy --all-features
  miri:
    runs-on: ubuntu-latest
    steps:
      - name: install nightly
        run: rustup install nightly && rustup default nightly
      - uses: actions/checkout@v3
      - name: install miri
        run: cargo install miri
      - name: run test
        run: cargo miri test --all-features
